volumes:
  double-take:

services:
  double-take:
    container_name: double-take
    image: double-take
    restart: unless-stopped
    volumes:
      - double-take:/.storage
    ports:
      - 3000:3000
      - 8080:8080
